### ISSUE TITLE
How to include LMStudio models automatically

### ISSUE THREAD

**Issue by theredwillow** [gokayfem/ComfyUI_VLM_nodes#99]
I'd like to add the necessary GGUF files automatically by adding my LM Studio cache folder to `extra_model_paths.yaml`. This way those models only need to be downloaded once.

Below is what I have so far, though it doesn't seem to be working...

```
lmstudio:
    base_path: C:\Users\<USER_NAME_HERE>\.cache\lm-studio

    Lavacheckpoints:
        files_for_internlm: models
```

I can't find any examples of how ComfyUI reads folders that are nested.
